### ISSUE TITLE
Defining routes

### ISSUE THREAD

**Issue by vladimir90** [Atinux/vue-adonis#10]
May this cause a problem? 

Route.any('*', 'WebAppController.render')

- How to define other routes? If I put another one below that

Route.any('*', 'WebAppController.render')
Route.get('/test', 'TestController.index')

It will return app.vue html template for any of the routes. Like I don't have any other routes.

**Comment by atinux** [comment]
You should define other routes **before** `Route.any('*', 'WebAppController.render')`
