### ISSUE TITLE
Not reloading on Windows 10

### ISSUE THREAD

**Issue by cannap** [Atinux/vue-adonis#4]
Hi, i tried to get this thing running it runs but not reloading

First i changed 
`    "dev": "nodemon --watch app --watch bootstrap --watch config --watch .env -x  'node' server.js",
`
to 
`    "dev": "nodemon --watch app --watch bootstrap --watch config --watch .env -x  && node server.js",
`
Looks like hmr is just not connecting
then i changed the dist folder to`   outputDir: '/dist/',`
Now i see the image and css loads but not hotreloading :/

looks like hmr is not connected i cant see some hmr output in the console

**Comment by atinux** [comment]
I cannot try on Windows 10, can you show me screenshots of the problem?

**Comment by cannap** [comment]
hi, i will come back in some hours 
the console is just empty there is no "HMR Connected" or a websocket connection

**Comment by atinux** [comment]
Hi @cannap, could you re-install vue-adonis with vue-cli and tell me if it's good now?

Thank you

**Comment by atinux** [comment]
Fixed in #5 

I'm closing this one as well.

**Comment by cannap** [comment]
Hu, i tested it works amazing!
