### ISSUE TITLE
How do I load a global css, js and where do all the images go?

### ISSUE THREAD

**Issue by abishekrsrikaanth** [Atinux/vue-adonis#7]

**Comment by atinux** [comment]
The global css should be put in the `resources/src/App.vue` file.

For the js, `resources/src/app.js`

For the images, you can add them in the `public/` folder.

**Comment by abishekrsrikaanth** [comment]
@Atinux What about css and js files loaded cdn? if I wanted to loaded js scripts right before body tag?

**Comment by atinux** [comment]
You can add them in [resources/views/app.njk](https://github.com/Atinux/vue-adonis/blob/master/template/resources/views/app.njk) @abishekrsrikaanth
